In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model   import LinearRegression
#loading data
data=pd.read_csv("C:\\Users\\KLECBKP\\Desktop\\cgpa.csv")
print(data)
#check null
print(data.isnull().sum())

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]
cgpa       0
package    0
dtype: int64


In [13]:
#define X and Y
x=data.iloc[:,[-2]].values
y=data.iloc[:,[-1]].values
print(x.shape,y.shape)


(200, 1) (200, 1)


In [14]:
#split the data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train,x_test,y_train,y_test)

[[7.87]
 [7.56]
 [7.77]
 [6.33]
 [6.14]
 [5.32]
 [8.13]
 [6.87]
 [7.39]
 [6.06]
 [6.07]
 [6.94]
 [7.63]
 [7.43]
 [6.5 ]
 [7.89]
 [7.09]
 [7.34]
 [5.11]
 [7.9 ]
 [6.22]
 [5.42]
 [5.64]
 [6.75]
 [7.57]
 [5.95]
 [4.57]
 [7.38]
 [8.37]
 [8.58]
 [5.09]
 [6.73]
 [8.15]
 [7.56]
 [7.25]
 [7.14]
 [7.35]
 [6.78]
 [7.15]
 [5.84]
 [6.94]
 [7.63]
 [7.28]
 [5.88]
 [6.29]
 [6.47]
 [8.2 ]
 [6.42]
 [7.78]
 [8.35]
 [6.66]
 [6.47]
 [5.42]
 [8.01]
 [8.28]
 [6.71]
 [8.44]
 [6.93]
 [7.13]
 [9.04]
 [6.96]
 [7.61]
 [7.05]
 [5.84]
 [5.99]
 [7.6 ]
 [6.37]
 [8.87]
 [6.68]
 [6.53]
 [8.22]
 [6.1 ]
 [9.06]
 [5.84]
 [7.18]
 [4.73]
 [5.12]
 [6.75]
 [8.71]
 [6.93]
 [7.33]
 [6.19]
 [6.89]
 [5.61]
 [8.63]
 [7.91]
 [7.4 ]
 [6.94]
 [6.51]
 [6.3 ]
 [9.16]
 [7.29]
 [7.12]
 [9.58]
 [6.63]
 [8.31]
 [8.65]
 [5.66]
 [6.61]
 [5.79]
 [8.6 ]
 [8.99]
 [8.21]
 [5.91]
 [6.84]
 [7.28]
 [8.25]
 [6.34]
 [8.11]
 [6.92]
 [7.88]
 [5.23]
 [7.3 ]
 [7.32]
 [7.93]
 [6.97]
 [6.86]
 [6.85]
 [6.05]
 [5.1 ]
 [5.94]
 [5.98]
 [6.22]
 [6.26]
 [5.12]


In [15]:
#define model
lr=LinearRegression()
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [16]:
#test the model
y_pred=lr.predict(x_test)
print(y_pred)
print(y_pred.shape)


[[3.30043032]
 [2.2303891 ]
 [2.57392865]
 [4.30289   ]
 [2.99068155]
 [2.40497477]
 [3.199058  ]
 [2.59082404]
 [2.17407114]
 [3.01884053]
 [3.18779441]
 [3.69465604]
 [3.64396988]
 [3.94245506]
 [3.07515849]
 [2.52324249]
 [1.48699204]
 [2.371184  ]
 [3.55949294]
 [3.54259755]
 [3.84108273]
 [2.54013787]
 [1.97695828]
 [2.89494102]
 [3.29479853]
 [3.37927547]
 [2.99631334]
 [3.09205387]
 [3.14274004]
 [4.33104898]
 [2.37681579]
 [3.50317498]
 [3.18779441]
 [3.23284877]
 [3.44122522]
 [1.819268  ]
 [2.99068155]
 [3.23848057]
 [4.37047155]
 [4.11704073]]
(40, 1)


In [17]:
#find the accuracy of train and test
trainaccuracy=lr.score(x_train,y_train)
testaccuracy=lr.score(x_test,y_test)
print(trainaccuracy)
print(testaccuracy)


0.7599494966156776
0.8125053422453364


In [18]:
from sklearn.metrics import mean_squared_error
msc=mean_squared_error(y_test,y_pred)
print(msc)
rmse=np.sqrt(msc)
print(rmse)

0.11482904070060843
0.33886433967091967


In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = lr.predict(x_test)

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))


Mean Absolute Error: 0.28802579908378084
Mean Squared Error: 0.11482904070060843
R2 Score: 0.8125053422453364


In [20]:
y_test

array([[2.83],
       [2.17],
       [2.48],
       [3.79],
       [2.51],
       [2.57],
       [2.94],
       [2.87],
       [1.61],
       [3.09],
       [3.48],
       [3.76],
       [3.55],
       [4.36],
       [2.85],
       [2.2 ],
       [1.53],
       [2.42],
       [3.99],
       [3.89],
       [3.49],
       [2.19],
       [1.37],
       [3.18],
       [3.34],
       [3.74],
       [2.37],
       [2.66],
       [2.83],
       [4.37],
       [1.87],
       [3.47],
       [2.72],
       [2.92],
       [3.42],
       [1.54],
       [2.46],
       [3.08],
       [4.02],
       [3.91]])

In [21]:
y_pred

array([[3.30043032],
       [2.2303891 ],
       [2.57392865],
       [4.30289   ],
       [2.99068155],
       [2.40497477],
       [3.199058  ],
       [2.59082404],
       [2.17407114],
       [3.01884053],
       [3.18779441],
       [3.69465604],
       [3.64396988],
       [3.94245506],
       [3.07515849],
       [2.52324249],
       [1.48699204],
       [2.371184  ],
       [3.55949294],
       [3.54259755],
       [3.84108273],
       [2.54013787],
       [1.97695828],
       [2.89494102],
       [3.29479853],
       [3.37927547],
       [2.99631334],
       [3.09205387],
       [3.14274004],
       [4.33104898],
       [2.37681579],
       [3.50317498],
       [3.18779441],
       [3.23284877],
       [3.44122522],
       [1.819268  ],
       [2.99068155],
       [3.23848057],
       [4.37047155],
       [4.11704073]])

In [23]:
cgpa=float(input("Enter your CGPA:"))
package=lr.predict([[cgpa]])
print("CGPA:",cgpa)
print("predicted package:",package[0][0],"LPA")


Enter your CGPA: 100


CGPA: 100.0
predicted package: 55.4058062177182 LPA


In [41]:
import streamlit as st
